title: OneStillForever 기술 블로그
description: 기술 학습 및 경험 공유 블로그
baseurl: ""
url: "https://onestillforever.github.io"

theme: minima

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives

# Jekyll Archives 설정
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: /category/:name/
    tag: /tag/:name/

# 저자 정보
author:
  name: OneStillForever
  email: your-email@example.com

# 페이지네이션
paginate: 10
paginate_path: "/page:num/"

# 마크다운 및 코드 하이라이트
markdown: kramdown
highlighter: rouge

# 포스트 URL 구조 (카테고리 → 제목)
collections:
  posts:
    output: true

permalink: /:categories/:title/

# 기본 설정
timezone: Asia/Seoul
encoding: utf-8
