title: OneStillForever 기술 블로그
description: 네트워크 엔지니어의 기술 학습 블로그
baseurl: ""
url: "https://onestillforever.github.io"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

author:
  name: OneStillForever
